# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (SUPABASE)
# ==========================================
# Cambiamos "postgresql://" por "jdbc:postgresql://" como exige Java
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require

# Tu usuario específico de Supabase
spring.datasource.username=postgres.enztojlfsykymmvazpwa

# Tu contraseña secreta
spring.datasource.password=ME3Mp477yLz8ZUES

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE (ORM)
# ==========================================
# "update" hace que Spring cree o actualice las tablas automáticamente leyendo tus @Entity
spring.jpa.hibernate.ddl-auto=update

# Para ver las consultas SQL en la consola de tu IDE (útil para debuggear)
spring.jpa.show-sql=true

# Formatea el SQL en la consola para que sea más fácil de leer
spring.jpa.properties.hibernate.format_sql=true